package com.smartparking.enums;

public enum NotificationType {
    SPOT_NOT_AVAILABLE,
    SPOT_RESERVED_VIOLATION,
    SPOT_RESERVED,
    RESERVATION_EXPIRED,
    RESERVATION_CANCELLED,
    RESERVATION_NOT_POSSIBLE,
    UNAUTHORIZED_CHECKIN,
    FINE_APPLIED,
    GENERAL_INFORMATION;
}
